version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=development
    ports:
      - "3000:3000"
      - "3478:3478/udp"
    volumes:
      - .:/app
      - /app/node_modules
